spring:
  application:
    name: spring-boot-demo

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: xxxxxxxx
    password: xxxxxxxxx

    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      initial-size: 5
    hikari:
      max-lifetime: 1800000

  mail:
    host: smtp.exmail.qq.com
    username: xxxxxxxxxxxxx
    password: xxxxxxxxxxxxx
    port: 465
    properties:
      from: 20190089@dgut.edu.cn
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  redis:
    database: 0
    host: localhost
    port: 6379
    password: xxxxxxxxxxx

  boot:
    admin:
      client:
        # spring boot admin server的注册地址,多个以逗号隔开,并把localhost换成ip
        url: http://localhost:8100
        instance:
          metadata:
            username: xxxxxxxxx
            password: xxxxxxxxx
          name: 科研绩效
          management-base-url: http://localhost:8080
          service-base-url: http://localhost:8080
        register-once: false
        username: xxxxxxxxx
        password: xxxxxxxxx
        enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: xxxxxxxxx
    password: xxxxxxxxx
    virtual-host: xxxxxxxx

mybatis-plus:
  # configuration:
    # default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  type-aliases-package: top.alvinsite.demo.model.entity,top.alvinsite.demo.model.dto,top.alvinsite.demo.model.dto.auth,top.alvinsite.demo.model.param,top.alvinsite.demo.model.vo
  # type-handlers-package: top.alvinsite.demo.typehandler
  config-location: classpath:mybatis/mybatis-config.xml
  type-enums-package: top.alvinsite.demo.model.enums
  global-config:
    banner: false

logging:
  level:
    root: info
  file:
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
    name: /var/log/performance/application.log

app:
  domain: test.alvinsite.top
  enable-username-password-login: false
  enable-unknown-exception-mail-alert: true

cas:
  dgut:
    domain: cas.dgut.edu.cn
    app-id: xxxxxxxxxxxxx
    app-secret: xxxxxxxxxxxx
    enable: true
    login-url: https://${cas.dgut.domain}/?appid=${cas.dgut.app-id}&state=
    logout-url: https://${cas.dgut.domain}/logout?callback=
    check-token: https://${cas.dgut.domain}/ssoapi/v2/checkToken
    user-info-server: https://${cas.dgut.domain}/oauth/getUserInfo



#需要暴露监控端口给spring boot admin server访问
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
