
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://172.31.40.7:3306/performance?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: performance
    password: xkmaGKwEbN4WKShr

  redis:
    host: 172.31.40.7
    password: candy.123

logging:
  level:
    root: info
    top.alvinsite.demo: debug

app:
  domain: 172.31.200.1:10300
  enable-username-password-login: true
  enable-unknown-exception-mail-alert: false

cas:
  dgut:
    domain: cas.zemcho.com
    app-id: springboot
    app-secret: caea6429f3b2
server:
  address: 0.0.0.0
  port: 8083
