
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://172.31.40.7:3306/performance?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: performance
    password: xkmaGKwEbN4WKShr

  redis:
    host: 172.31.40.7
    password: candy.123

  boot:
    admin:
      client:
        # spring boot admin server的注册地址,多个以逗号隔开,并把localhost换成ip
        url: http://172.31.40.7:8100
        instance:
          management-base-url: http://172.31.40.7:8083
          service-base-url: http://172.31.40.7:8083

logging:
  level:
    root: info
    top.alvinsite.demo: debug

app:
  domain: 219.222.186.51:10300
  enable-username-password-login: true
  enable-unknown-exception-mail-alert: true

cas:
  dgut:
    domain: cas.zemcho.com
    app-id: springboot
    app-secret: caea6429f3b2
server:
  port: 8083
