
spring:
  datasource:
    url: jdbc:mysql://172.31.40.7:3306/performance?serverTimezone=UTC
    username: performance
    password: xkmaGKwEbN4WKShr

  redis:
    host: 172.31.40.7


logging:
  level:
    root: debug

app:
  domain: 172.31.200.1:10300

cas:
  dgut:
    domain: cas.zemcho.com
    app-id: springboot
    app-secret: caea6429f3b2
server:
  address: 0.0.0.0
  port: 8081

debug: false

