

spring:
  application:
    name: performance

  datasource:
    #url: jdbc:mysql://localhost:3306/research_performance?serverTimezone=UTC
    #username: root
    #password: root
    url: jdbc:mysql://172.31.150.19:3306/performance?serverTimezone=UTC
    username: performance
    password: RBE872d6Y8KzX5HK

    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 50
      max-idle: 10
      max-wait: 10000
      initial-size: 5
    hikari:
      max-lifetime: 1800000

  mail:
    host: smtp.exmail.qq.com
    username: 20190089@dgut.edu.cn
    password: Angel123
    port: 465
    properties:
      from: 20190089@dgut.edu.cn
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  redis:
    database: 0
    host: 172.31.150.19
    port: 6379
    password: candy.123

  boot:
    admin:
      client:
        # spring boot admin server的注册地址,多个以逗号隔开,并把localhost换成ip
        url: http://172.31.40.7:8100
        instance:
          metadata:
            username: admin
            password: candy.123
          name: 科研绩效
        register-once: false
        username: admin
        password: candy.123
        enabled: true

  rabbitmq:
    host: 172.31.40.7
    port: 5672
    username: alvin
    password: candy.123
    virtual-host: test

mybatis-plus:
  # configuration:
    # default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  type-aliases-package: top.alvinsite.demo.model.entity,top.alvinsite.demo.model.dto,top.alvinsite.demo.model.dto.auth,top.alvinsite.demo.model.params,top.alvinsite.demo.model.vo
  # type-handlers-package: top.alvinsite.demo.typehandler
  config-location: classpath:mybatis/mybatis-config.xml
  type-enums-package: top.alvinsite.demo.model.enums
  global-config:
    banner: false

logging:
  level:
    root: info
  file:
    max-history: 30
    max-size: 10MB
    total-size-cap: 300MB
    name: /var/log/performance/application.log

app:
  domain: csjx.dgut.edu.cn
  enable-username-password-login: false
  enable-unknown-exception-mail-alert: true

cas:
  dgut:
    domain: cas.dgut.edu.cn
    app-id: performance
    app-secret: 13e787fff1d0
    enable: true
    login-url: https://${cas.dgut.domain}/?appid=${cas.dgut.app-id}&state=
    logout-url: https://${cas.dgut.domain}/logout?callback=
    check-token: https://${cas.dgut.domain}/ssoapi/v2/checkToken
    user-info-server: https://${cas.dgut.domain}/oauth/getUserInfo



#需要暴露监控端口给spring boot admin server访问
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
