server:
  port: 8085

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/research_performance?serverTimezone=UTC
    # username: root
    # password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:mysql://172.31.40.7:3306/performance?serverTimezone=UTC
    url: jdbc:p6spy:mysql://172.31.40.7:3306/performance?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: performance
    password: xkmaGKwEbN4WKShr
    hikari:
      max-lifetime: 1200000
  redis:
    host: 127.0.0.1
    password:

  devtools:
    restart:
      enabled: true

cas:
  dgut:
    domain: cas.zemcho.com
    app-id: security
    app-secret: 63ea3412464a

app:
  domain: 172.31.200.1:10301
  enable-username-password-login: true
  enable-unknown-exception-mail-alert: false

logging:
  level:
    root: info
    top.alvinsite.demo.controller: debug
    top.alvinsite.demo.core: debug
debug: false
