spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/research_performance?serverTimezone=UTC
    # username: root
    # password: root
    url: jdbc:mysql://172.31.40.7:3306/performance?serverTimezone=UTC
    username: performance
    password: xkmaGKwEbN4WKShr

  redis:
    host: 127.0.0.1
    password:

cas:
  dgut:
    domain: cas.zemcho.com
    app-id: donationdev
    app-secret: e41690c440fa

logging:
  level:
    root: info
    top.alvinsite.demo: info

debug: false